version: "2"
services:
  web:
    build: .
    ports:
    - "9090:9090"
    volumes:
      - data-volume:/data/uploads
    environment:
      - STORAGE_PATH=/data/uploads/
      - LOGGER_URL=http://logger.home.localnet:3100
volumes:
  data-volume:
  
