name: Docker Image CI

on:
  push:
    branches: ["ci_test"]
  pull_request:
    branches: ["ci_test"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag zenpic_image_store:$(date +%s)
